tipo = input('Escreva algo para descobrir o tipo:')
print(type(tipo))
print('O tipo é numérico?', tipo.isnumeric())
print('O tipo é alfanumérico?', tipo.isalnum())
print('O tipo é alfabético?', tipo.isalpha())
print('O tipo é minúsculo?', tipo.islower())
print('O tipo é maiúsculo?', tipo.isupper())
print('O tipo é decimal?', tipo.isdecimal())
print('O tipo é título?', tipo.istitle())
print('O tipo é espaço?', tipo.isspace())